---

- name: enable epel
  package:
    name: epel-release
    state: present
  when: ansible_distribution == 'CentOS'

- name: install redis packages
  package:
    name: '{{ redis_packages }}'
    state: present
